// ─── RdivExport – Supabase Database Schema Types ───────────────────────────
// Simplified generated types matching the database schema.

export type UUID = string
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// ─── Table Row Types ────────────────────────────────────────────────────────

export interface PharmacyRow {
  id: UUID
  name: string
  code: string
  address: string | null
  phone: string | null
  whatsapp_number: string | null
  email: string | null
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface ProfileRow {
  id: UUID
  full_name: string
  email: string
  phone: string | null
  role: 'pharmacy_user' | 'main_requisitionist'
  pharmacy_id: UUID | null
  avatar_url: string | null
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface ProductRow {
  id: UUID
  name: string
  description: string | null
  code: string | null
  main_depot_stock: number
  unit: string | null
  category: string | null
  min_stock_threshold: number | null
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface RequisitionRow {
  id: UUID
  reference_number: string
  pharmacy_id: UUID
  created_by: UUID
  status: 'draft' | 'pending' | 'validated' | 'delivered' | 'cancelled'
  comment: string | null
  validated_by: UUID | null
  validated_at: string | null
  delivered_by: UUID | null
  delivered_at: string | null
  cancelled_by: UUID | null
  cancelled_at: string | null
  cancel_reason: string | null
  created_at: string
  updated_at: string
}

export interface RequisitionItemRow {
  id: UUID
  requisition_id: UUID
  product_id: UUID
  product_name: string
  quantity_requested: number
  quantity_delivered: number | null
  created_at: string
}

export interface DeliveryChecklistRow {
  id: UUID
  requisition_id: UUID
  delivered_by: UUID
  notes: string | null
  items_checked: boolean
  signed_at: string | null
  created_at: string
  updated_at: string
}

export interface AuditLogRow {
  id: UUID
  user_id: UUID
  action: string
  entity_type: string
  entity_id: UUID
  details: Json | null
  ip_address: string | null
  user_agent: string | null
  created_at: string
}

// ─── Insert Types (created_at / updated_at omitted – generated by DB) ─────

export interface PharmacyInsert {
  id?: UUID
  name: string
  code: string
  address?: string | null
  phone?: string | null
  whatsapp_number?: string | null
  email?: string | null
  is_active?: boolean
}

export interface ProfileInsert {
  id?: UUID
  full_name: string
  email: string
  phone?: string | null
  role: 'pharmacy_user' | 'main_requisitionist'
  pharmacy_id?: UUID | null
  avatar_url?: string | null
  is_active?: boolean
}

export interface ProductInsert {
  id?: UUID
  name: string
  description?: string | null
  code?: string | null
  main_depot_stock?: number
  unit?: string | null
  category?: string | null
  min_stock_threshold?: number | null
  is_active?: boolean
}

export interface RequisitionInsert {
  id?: UUID
  reference_number: string
  pharmacy_id: UUID
  created_by: UUID
  status?: 'draft' | 'pending' | 'validated' | 'delivered' | 'cancelled'
  comment?: string | null
  validated_by?: UUID | null
  validated_at?: string | null
  delivered_by?: UUID | null
  delivered_at?: string | null
  cancelled_by?: UUID | null
  cancelled_at?: string | null
  cancel_reason?: string | null
}

export interface RequisitionItemInsert {
  id?: UUID
  requisition_id: UUID
  product_id: UUID
  product_name: string
  quantity_requested: number
  quantity_delivered?: number | null
}

export interface DeliveryChecklistInsert {
  id?: UUID
  requisition_id: UUID
  delivered_by: UUID
  notes?: string | null
  items_checked?: boolean
  signed_at?: string | null
}

export interface AuditLogInsert {
  id?: UUID
  user_id: UUID
  action: string
  entity_type: string
  entity_id: UUID
  details?: Json | null
  ip_address?: string | null
  user_agent?: string | null
}

// ─── Update Types (all fields optional) ────────────────────────────────────

export interface PharmacyUpdate {
  name?: string
  code?: string
  address?: string | null
  phone?: string | null
  whatsapp_number?: string | null
  email?: string | null
  is_active?: boolean
}

export interface ProfileUpdate {
  full_name?: string
  email?: string
  phone?: string | null
  role?: 'pharmacy_user' | 'main_requisitionist'
  pharmacy_id?: UUID | null
  avatar_url?: string | null
  is_active?: boolean
}

export interface ProductUpdate {
  name?: string
  description?: string | null
  code?: string | null
  main_depot_stock?: number
  unit?: string | null
  category?: string | null
  min_stock_threshold?: number | null
  is_active?: boolean
}

export interface RequisitionUpdate {
  reference_number?: string
  pharmacy_id?: UUID
  status?: 'draft' | 'pending' | 'validated' | 'delivered' | 'cancelled'
  comment?: string | null
  validated_by?: UUID | null
  validated_at?: string | null
  delivered_by?: UUID | null
  delivered_at?: string | null
  cancelled_by?: UUID | null
  cancelled_at?: string | null
  cancel_reason?: string | null
}

export interface RequisitionItemUpdate {
  quantity_requested?: number
  quantity_delivered?: number | null
}

export interface DeliveryChecklistUpdate {
  notes?: string | null
  items_checked?: boolean
  signed_at?: string | null
}

// ─── Database Interface (Supabase generated schema) ─────────────────────────

export interface Database {
  public: {
    Tables: {
      pharmacies: {
        Row: PharmacyRow
        Insert: PharmacyInsert
        Update: PharmacyUpdate
        Relationships: []
      }
      profiles: {
        Row: ProfileRow
        Insert: ProfileInsert
        Update: ProfileUpdate
        Relationships: [
          {
            foreignKeyName: 'profiles_pharmacy_id_fkey'
            columns: ['pharmacy_id']
            referencedRelation: 'pharmacies'
            referencedColumns: ['id']
          }
        ]
      }
      products: {
        Row: ProductRow
        Insert: ProductInsert
        Update: ProductUpdate
        Relationships: []
      }
      requisitions: {
        Row: RequisitionRow
        Insert: RequisitionInsert
        Update: RequisitionUpdate
        Relationships: [
          {
            foreignKeyName: 'requisitions_pharmacy_id_fkey'
            columns: ['pharmacy_id']
            referencedRelation: 'pharmacies'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'requisitions_created_by_fkey'
            columns: ['created_by']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'requisitions_validated_by_fkey'
            columns: ['validated_by']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'requisitions_delivered_by_fkey'
            columns: ['delivered_by']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'requisitions_cancelled_by_fkey'
            columns: ['cancelled_by']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      requisition_items: {
        Row: RequisitionItemRow
        Insert: RequisitionItemInsert
        Update: RequisitionItemUpdate
        Relationships: [
          {
            foreignKeyName: 'requisition_items_requisition_id_fkey'
            columns: ['requisition_id']
            referencedRelation: 'requisitions'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'requisition_items_product_id_fkey'
            columns: ['product_id']
            referencedRelation: 'products'
            referencedColumns: ['id']
          }
        ]
      }
      delivery_checklists: {
        Row: DeliveryChecklistRow
        Insert: DeliveryChecklistInsert
        Update: DeliveryChecklistUpdate
        Relationships: [
          {
            foreignKeyName: 'delivery_checklists_requisition_id_fkey'
            columns: ['requisition_id']
            referencedRelation: 'requisitions'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'delivery_checklists_delivered_by_fkey'
            columns: ['delivered_by']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      audit_logs: {
        Row: AuditLogRow
        Insert: AuditLogInsert
        Update: Record<string, never>
        Relationships: [
          {
            foreignKeyName: 'audit_logs_user_id_fkey'
            columns: ['user_id']
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: 'pharmacy_user' | 'main_requisitionist'
      requisition_status: 'draft' | 'pending' | 'validated' | 'delivered' | 'cancelled'
    }
  }
}
